 <?php if (!empty($this->errorsMessages)): ?>
		<div class="alert alert-error">
		   <button type="button" class="close" data-dismiss="alert">×</button>
		    <?php foreach ($this->errors as $key => $error): ?>
		    	<?php if (!empty($error)): ?>
		    		<label for="<?php echo $key ?>">
		    			<strong>
		    			    <?php echo $this->form->getElement($key)->getLabel()." : "; ?>
		    			</strong>
		    			<?php foreach ($error as $e): ?>
		    				<?php echo $this->errorsMessages[$key][$e]; ?>
		    			<?php endforeach; ?>
		    		</label>
		    	<?php endif; ?>
		    <?php endforeach; ?>
		     
		</div>
<?php endif; ?>

<?php if (!empty($this->customerror)): ?>
	<div class="alert alert-error">
		<button type="button" class="close" data-dismiss="alert">×</button>
		<div>
   			<?php echo $this->customerror;  ?>
		</div>
	</div>
<?php endif; ?>

<?php if(!empty($this->success)): ?>
   <div class="alert alert-success">
   		<button type="button" class="close" data-dismiss="alert">×</button>
   		<div>
   			<?php echo $this->success;  ?>
		</div>
   </div>
<?php endif; ?>
<form action="" method="post">
	<div class="row-fluid">
		<div class="span7">
			<div class="form-horizontal">
			<?php 
				echo $this->form->content_title; 
				echo $this->form->content;
			?>
		</div>	
		</div>
		<div class="span5">
		<?php 
			echo $this->form->categorys; 
			echo $this->form->description; 
			echo $this->form->keywords; 
		?>
		</div> 
	</div>
	<?php echo $this->form->add_submit; ?>
</form>


		<?php
		
		$lang = Zend_Registry::get('Zend_Locale');
		$editor_about_us_arm = "

	CKEDITOR.replace( 'content',
					{
						toolbar : 'Admin',
						language: '{$lang}'
					});
";
		$this->headScript()->appendScript($editor_about_us_arm);
		echo $this->headScript();
		$this->headScript()->exchangeArray(array());
		?>