<div class="login_forms">
    <?php if (!empty($this->errorsMessages)): ?>
    <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">×</button>
    			        <?php
                            foreach ($this->errors as $key => $error):
                        ?>
    				<?php if (!empty($error)): ?>
    				<div>
    				<strong>
    				    <?php echo $this->login_form->getElement($key)->getLabel()." : "; ?>
    				 </strong>
    				<?php foreach ($error as $e): ?>
    					<?php echo $this->errorsMessages[$key][$e]; ?>
    				<?php endforeach; ?>
    				</div>
    				<?php endif; ?>
    				<?php endforeach; ?>
     
     </div>
   <?php endif; ?>
   <h3> <?php echo $this->translate('Please sign in'); ?></h3>
    <?php echo $this->login_form; ?>
</div>