<?php echo $this->doctype("XHTML1_STRICT"); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php
echo $this->headMeta();
echo $this->headTitle();

/*
 * this->headLink(array('rel' => 'icon', 'type'=>'image/x-icon', 'href' =>
 * $this->baseUrl('/public/images/favicon.ico')), 'PREPEND');
 */
$this->headLink()->appendStylesheet(
        $this->baseUrl('/public/css/corner.css'),
        'screen');
$this->headLink()->appendStylesheet($this->baseUrl('/public/css/reset.css'), 
        'screen');
$this->headLink()->appendStylesheet($this->baseUrl('/public/css/main.css'), 
        'screen');

/* other plugins css START */

$this->headLink()->appendStylesheet(
        $this->baseUrl('/public/js_css_plugins/jquery_ui/vader/jquery-ui-1.9.2.min.css'), 
        'screen');
$this->headLink()->appendStylesheet(
        $this->baseUrl('/public/js_css_plugins/fancybox/jquery.fancybox.css'), 
        'screen');
$this->headLink()->appendStylesheet(
        $this->baseUrl('/public/js_css_plugins/slidesjs/news_slider.css'),
        'screen');


/* other plugins css END */

/*************** javascript start  ******************/

$this->headScript()->appendFile(
        $this->baseUrl('/public/js/jquery-1.8.3.min.js'));
$this->headScript()->appendFile(
        $this->baseUrl(
                '/public/js_css_plugins/jquery_ui/jquery-ui-1.9.2.min.js'));
$this->headScript()->appendFile(
        $this->baseUrl(
                '/public/js_css_plugins/jquery_ui/jquery.ui.touch-punch.js'));
$this->headScript()->appendFile(
        $this->baseUrl(
                '/public/js_css_plugins/fancybox/jquery.mousewheel-3.0.6.pack.js'));
$this->headScript()->appendFile(
        $this->baseUrl('/public/js_css_plugins/fancybox/jquery.fancybox.js'));
/*$this->headScript()->appendFile(
        $this->baseUrl('/public/js_css_plugins/corner/curvycorners.js'));
$this->headScript()->appendFile(
        $this->baseUrl('/public/js_css_plugins/corner/jquery.corner.js'));*/
$this->headScript()->appendFile(
        $this->baseUrl('/public/js_css_plugins/corner/DD_roundies_0.0.2a.js'));
/*$this->headScript()->appendFile(
        $this->baseUrl(
                '/public/js_css_plugins/easy_slider/easySlider1.7.js'));*/
/*$this->headScript()->appendFile(
        $this->baseUrl(
                '/public/js_css_plugins/box_shadow/jquery.boxshadow.js'));*/
$this->headScript()->appendFile(
        $this->baseUrl(
                '/public/js_css_plugins/slidesjs/slides.min.jquery.js'));

/** MY javascript START **/

$this->headScript()->appendFile($this->baseUrl('/public/js/my_js_styles.js'));
//$this->headScript()->appendFile($this->baseUrl('/public/js/my_js_corner2.js'));
$this->headScript()->appendFile($this->baseUrl('/public/js/ie.js','text/javascript', array('conditional' => 'IE')));
$this->headScript()->appendFile(
        $this->baseUrl('/public/js/my_js_functional.js'));

/** MY javascript END **/

/*************** javascript END  ******************/

echo $this->headLink();
echo $this->headScript();

$this->headLink()->exchangeArray(array());
$this->headScript()->exchangeArray(array());
?>
<script type="text/javascript">
<!--
$(document).ready(function(){
    $('#menu li').hover(function(){
            $(this).find('ul:first').css({visibility: "visible",display: "none"}).fadeIn(400); // effect 1
           //  $(this).find('ul:first').css({visibility: "visible",display: "none"}).slideDown(400); // effect 2
        },function(){
            $(this).find('ul:first').css({visibility: "hidden"});
        });
});


//-->
</script>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-37426650-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<style>
<!--



#menu ul {display:inline-block;} 

/*#menu li {display:inline-block;}*/
#menu ul ul {position:absolute; left:-9999px; background: #51b3e1;}


#menu ul.level1 li.level1-li {float:left; display:block; position:relative;}

#menu b {position:absolute;}

#menu a {display:block; color:white; line-height:25px; text-decoration:none;padding:0 20px;}
#menu ul.level1 li.level1-li a.level1-a {float:left;}

#menu ul li:hover > ul {visibility:visible; left:0; top:21px;}
#menu ul ul li:hover > ul {visibility:visible; left:100%; top:auto; margin-top:-25px; margin-left:-4px;}
#menu li.left:hover > ul {visibility:visible; left:auto; right:0; top:25px;}
#menu li.left ul li:hover > ul {visibility:visible; left:auto; right:100%; top:auto; margin-top:-25px; margin-right:-4px;}


#menu a:hover ul {left:0; top:23px;}
#menu li.left a:hover ul {left:auto; right:-1px; top:23px;}

#menu li.left ul a {text-align:right;}


#menu a:hover a:hover ul, 
#menu a:hover a:hover a:hover ul {left:100%; visibility:visible;}
#menu li.left a:hover a:hover ul, 
#menu li.left a:hover a:hover a:hover ul {left:auto; right:0; visibility:visible;}

#menu a:hover ul ul, 
#menu a:hover a:hover ul ul {left:-9999px;}
#menu li.left a:hover ul ul, 
#menu li.left a:hover a:hover ul ul {left:-9999px;}

#menu li a.drop {background:transparent url(/white-down.gif) no-repeat right center;}
#menu li a.fly {background:transparent url(/white-right.gif) no-repeat right center;}
#menu li.left ul a.fly {background:transparent url(/white-left.gif) no-repeat left center;}

/*#menu li a:hover,
#menu li a.fly:hover {color:white; background-color:#c0c0c8;}*/

#menu > ul > li:hover > a{
	background: #20688a;
}
#menu > ul > li:hover li a{
	color: black;
}
#menu > ul > li:hover li a:hover{
	color: white;
}
#menu > ul > li li{
	border-bottom: 1px solid black;
	padding:0px 5px 5px 5px;
}
/*#menu li:hover > a,
#menu ul li:hover > a.fly {color:#c60; background-color:#c0c0c8;}*/
#menu ul li:hover > a.fly {color:white; background-color:#c0c0c8;;}

#menu table {position:absolute; height:0; width:0; left:0; border-collapse:collapse; margin-top:-6px;}
#menu table table {position:absolute; left:99%; height:0; width:0; border-collapse:collapse; margin-top:-30px; margin-left:-4px;}

#menu li.left table {position:absolute; height:0; width:0; left:auto; right:0; border-collapse:collapse; margin-top:-4px;}
#menu li.left table table {position:absolute; left:auto; right:100%; height:0; width:0; border-collapse:collapse; margin-top:-30px; margin-right:-4px;}
-->
</style>

</head>
<body>
	<div id="center">
		<div id="top_bar">
			<ul class="languge_bar">
			<?php  foreach ($this->layout()->all_languages as $lang): ?>
				<li>
				<?php if (Zend_Registry::get("Zend_Locale") == "{$lang['lang_short_name']}"): ?> 
					<a class='lang_select'
					href="<?php echo $this->url(array("lang" => "{$lang['lang_short_name']}"));?>">
					<?php else: ?>
					<a
						href="<?php echo $this->url(array("lang" => "{$lang['lang_short_name']}"));?>">					
				<?php endif; ?> 
					<?php if (!empty($lang['language_image'])): ?> 
						<img alt="lang"
							src="<?php echo $this->baseUrl("/public/images/lang_icon/{$lang['language_image']}") ?>" /> 
					<?php endif; ?> 
					<?php echo $lang['lang_full_name'] ?> </a>
				
				</li>
			<?php endforeach; ?>
			</ul>
			<ul class="login_reg_bar">
				<li><a id="login_botton" href="javascript:">Մուտք</a></li>
				<li><a href="#"> Գրանցվել </a></li>
			</ul>
			<div class="clear"></div>
			<div id="login_form_box">dfasdfasdfasdf</div>
		</div>
		<div id="site_content_bar">
			<div id="header_bar">
				<a class="logo" href="#"> <img alt="logo"
					src="<?php echo $this->baseUrl('/public/images/logo.png') ?>" />
				</a>
				<div class="top_right_info">
					<h2>
						<a href="#"> <?php echo $this->translate('State engineering university of Armenia'); ?></a>
					</h2>
					<h3>
						<a href="#"> <?php echo $this->translate('Computer systems and Informatics'); ?></a>
					</h3>

					<h1> <?php echo $this->translate('Information Security and Software Development department'); ?> </h1>

					<div class="top_menu">
			

    <div id="menu">
    <?php  echo $this->layout()->top_menu; ?>
    </div>
 
					</div>
				</div>
				<div class="clear"></div>
			</div>
			<div id="content_bar">
				<div class="left_column">
					<?php //echo $this->layout()->left_menu; ?>
				</div>
				<div class="right_column">
			        <?php echo $this->layout()->content; ?>
			    </div>
			    <div class="clear"></div>
			</div>
			<div id="footer_bar">footer</div>
		</div>

	</div>
	<script type="text/javascript">
			/*jQuery(function($){
				$.fancybox({
					href : '#mid',
					autoSize	: false,
					height: $('#mid').height(),
					helpers     : {
			            overlay : {
			                closeClick: false
			            }
			        }
				});
			});*/
		</script>
</body>
</html>