<?php echo $this->doctype("XHTML1_STRICT"); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php
echo $this->headMeta();
echo $this->headTitle();

/*
 * this->headLink(array('rel' => 'icon', 'type'=>'image/x-icon', 'href' =>
 * $this->baseUrl('/public/images/favicon.ico')), 'PREPEND');
 */
/*$this->headLink()->appendStylesheet(
        $this->baseUrl('/public/js_css_plugins/slidesjs/news_slider.css'),
        'screen');*/
$this->headLink()->appendStylesheet(
		$this->baseUrl('/public/css/main.css'),'screen');
$this->headLink()->appendStylesheet(
 $this->baseUrl('/public/js_css_plugins/bootstrap/css/bootstrap.min.css'),
		'screen');

/*************** javascript start  ******************/

$this->headScript()->appendFile(
        $this->baseUrl('/public/js/jquery-1.8.3.min.js'));
$this->headScript()->appendFile(
		$this->baseUrl('/public/js_css_plugins/bootstrap/js/bootstrap.min.js'));

//$this->headScript()->appendFile($this->baseUrl('/public/js/ie.js','text/javascript', array('conditional' => 'IE')));
/*$this->headScript()->appendFile(
        $this->baseUrl('/public/js/my_js_functional.js'));*/

/*************** javascript END  ******************/

echo $this->headLink();
echo $this->headScript();

$this->headLink()->exchangeArray(array());
$this->headScript()->exchangeArray(array());
?>

</head>
<body>
	<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">Project name</a>
          <!-- if auth Start  -->
          <?php 
          /*<div class="btn-group pull-right">
    		 <button class="btn">
    		 	<i class="icon-user"></i>
    			User
    		 </button>
			<button class="btn dropdown-toggle" data-toggle="dropdown">
				<span class="caret"></span>
			</button>
    		<ul class="dropdown-menu">
    			<li><a href="#"><i class="icon-pencil"></i> Edit</a></li>
    			<li class="divider"></li>
    			<li><a href="#"><i class="icon-off"></i> Log Out </a></li>
    		</ul>
    	 </div>
    	 */
    	 ?>
    	 <!-- if auth END  -->
    	 
          <div class="nav-collapse collapse">
             <ul class="nav pull-right">
	          <li class="dropdown">
	          	<a href="#" class="dropdown-toggle" data-toggle="dropdown">Login <b class="caret"></b></a>
	          	  <ul class="dropdown-menu">
	                 <li>
							<form style="padding: 10px">
							  <fieldset>
							    <input type="text" placeholder="Type something…">
							    <input type="text" placeholder="askdfhkh" />
							    <label class="checkbox">
							      <input type="checkbox"> Check me out
							    </label>
							    <input type="submit" value="Log in" class="btn pull-right" />
							  </fieldset>
							</form>  
	                 </li>
	              </ul>
	          </li>
          	<li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                          <li><a href="#">Action</a></li>
                          <li><a href="#">Another action</a></li>
                          <li><a href="#">Something else here</a></li>
                          <li class="divider"></li>
                          <li><a href="#">Separated link</a></li>
                        </ul>
                      </li>
          </ul>
          
          
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    	<header>
			  <div class="container-fluid" id="header_about">
			    <p class="lead"> 
			    	<a href="#"> <?php echo $this->translate('State engineering university of Armenia'); ?></a>
			    	<br />
			    	<a href="#"> <?php echo $this->translate('Computer systems and Informatics'); ?></a> 
			    </p>
			    <h1> <?php echo $this->translate('Information Security and Software Development department'); ?> </h1>
			  </div>
			</header>
    <div class="container-fluid">
    	<div class="row-fluid">
    		<div class="span3" style="position: relative;">
    			<div class="well sidebar-nav sidebar-nav-fixed">
					<ul class="nav nav-list">
						<li class="nav-header">Sidebar</li>
						<li class="dropdown-submenu">
							<a href="#">Dropdown</a>
							<ul class="dropdown-menu">
								<li><a href="#">6565</a></li>
								<li><a href="#">2sw</a></li>
								<li><a href="#">eqwr</a></li>
								<li><a href="#">erhf</a></li>
							</ul> 
						</li>
						<li> <a href="#">Dropsadasddown</a> </li>
						<li> <a href="#">efd596</a> </li>
						<li> <a href="#">easf</a> </li>
						<li> <a href="#">Droasdfpdown</a> </li>
					</ul>
				</div>
    		</div>
    	
    		<div class="span9">
    		<!-- 
    			<div class="top-bg">
		          	<h3>
						<a href="#"> <?php echo $this->translate('State engineering university of Armenia'); ?></a>
				 	</h3>
					<h3>
						<a href="#"> <?php echo $this->translate('Computer systems and Informatics'); ?></a>
					</h3>
		
					<h1> <?php echo $this->translate('Information Security and Software Development department'); ?> </h1>
     			</div>
     			-->
     			<div class="container-fluid">
	 <?php for($i=0;$i<100; $i++): ?>
	 	ashmdbsad ashmdbsad loremashmdbsad loremashmdbsad loremashmdbsad loremashmdbsad loremashmdbsad loremashmdbsad loremashmdbsad loremashmdbsad loremashmdbsad loremashmdbsad loremashmdbsad loremashmdbsad loremashmdbsad loremashmdbsad loremashmdbsad loremashmdbsad loremashmdbsad loremashmdbsad loremashmdbsad loremashmdbsad loremashmdbsad loremashmdbsad loremashmdbsad loremlorem
	 <?php endfor; ?>
	 </div>
    		</div>
    	</div>
	 </div>	
</body>
</html>